monitor=,1920x1080,auto,1.2
monitor=HDMI-A-1,1920x1080,auto,1

# monitor=name,res@hz,pos,scale,additional_options

# name: device identifier found via hyprctl monitors
# res@hz: pixel dimensions and refresh rate or preferred/highrr
# pos: coordinate location in global space such as 0x0 or 1920x0
# scale: interface magnification factor like 1 for 100% or 2 for 200%
# transform: rotation index from 0 to 7 for portrait or flipped modes
# mirror: name of the monitor to duplicate for mirrored output
# bitdepth: color depth value such as 8 or 10
# vrr: adaptive sync setting 0 for off, 1 for on, 2 for fullscreen
# disable: keyword to power off the specific display output