windowrule = match:class ^(wofi)$, \
             float on, \
             size 350 450, \
             move 73% 30, \
             pin on, \
             stay_focused on
windowrule = match:title ^(.*Network Manager.*)$, \
             float on
