windowrule = match:class ^(wofi)$, float on
windowrule = match:class ^(wofi)$, size 300 400
windowrule = match:class ^(wofi)$, move 75% 30
windowrule = match:class ^(wofi)$, pin on
windowrule = match:class ^(wofi)$, stay_focused on