windowrule = match:class ^(wofi)$, \
             float on, \
             size 500 400, \
             move 73% 30, \
             pin on, \
             stay_focused on
windowrule = match:title ^(.*Network Manager.*)$, \
             float on, \
             size 500 400, \
             move center
windowrule = match:title ^(Hyprshot)$, match:class ^(python3)$, \
             float on, \
             size 500 400, \
             move center
windowrule = match:class ^(nmgui)$, \
             float on, \
             size 500 400, \
             move center
windowrule = match:class ^(blueman-manager)$, \
             float on, \
             size 500 400, \
             move center
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, \
             float on, \
             size 500 400, \
             move center
windowrule = match:class ^(pavucontrol)$, \
             float on, \
             size 500 400, \
             move center
windowrule = match:class ^(waypaper)$, \
             float on, \
             size 500 400, \
             move center


# Example windowrules that are useful
windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Wofi rules
layerrule {
    name = wofi-blur
    match:namespace = wofi
    blur = on
    ignore_alpha = 0.5
}
