# Załaduj tapetę do pamięci
preload = ~/.config/hypr/wallpaper.jpg

# Ustaw tapetę na monitorze (pusty monitor oznacza wszystkie)
wallpaper = ,~/.config/hypr/wallpaper.jpg

# Wyłącz renderowanie splash screena (opcjonalne)
splash = false
